linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - unconvert
    - golint
    - staticcheck

linter-settings:
  goimports:
    local-prefixes: 'github.com/abustany/goretro/retro'
