name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2'

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Run backend tests
        run: go test -v ./...

      - name: Run backend linter
        uses: golangci/golangci-lint-action@v0.1.7
        with:
          version: v1.26
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # We also build the Docker image for PRs, since we want to check those
      # don't break the build. We just don't push it.
      - name: Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: abustany/goretro
          tags: latest
          add_git_labels: true
          push: ${{ github.ref == 'refs/heads/master' }}
